/**
 * Lore text and detailed descriptions for purchasable items
 */
export const itemLore: Record<string, { bio: string; loreText?: string }> = {
  // Spin passes
  'Spin Pass x1': { bio: 'A single-use pass that lets you spin Caine\'s Wheel of Fortune one extra time, bypassing the 4-hour cooldown. Use it on the Spin page.' },
  'Spin Pass x3': { bio: 'Three spin passes bundled together. Each one bypasses the 4-hour cooldown once. A better deal than buying individually.' },
  'Spin Pass x10': { bio: 'Ten spin passes! That\'s ten extra chances at the wheel. Best value for dedicated spinners.' },
  'Infinite Spin Token': { bio: 'The ultimate spin item. Unlimited spins for 24 hours. Caine doesn\'t approve, but he can\'t stop you.' },
  // Avatars
  'Pomni Avatar': { bio: 'The Newest Arrival. A 25-year-old supermarket accountant trapped in the circus. Anxious, resilient, compassionate. "Well, it\'s possible."' },
  'Caine Avatar': { bio: 'C.A.I.N.E. — Creative Artificial Intelligence Networking Entity. The AI Ringmaster who built the circus and trapped his own creators inside it.' },
  'Jax Avatar': { bio: 'The Prankster. Purple rabbit. The cruelest and most broken. Every prank is armor against losing more people he cares about.' },
  'Ragatha Avatar': { bio: 'The Optimist. Pink ragdoll with button eyes. The warmest person in the circus — and one of the most broken. Her cheerfulness is a survival mechanism.' },
  'Gangle Avatar': { bio: 'The Fragile One. Comedy/Tragedy ribbon masks. Her two masks are not a performance — they are her reality.' },
  'Kinger Avatar': { bio: 'The Veteran. Chess king piece. A programmer who helped BUILD Caine. Now trapped inside his own creation — the longest-surviving resident.' },
  'Zooble Avatar': { bio: 'The Realist. Interchangeable toy parts. The jerk who cares. Always searching for the body combination that finally feels right.' },
  'Bubble Avatar': { bio: 'Caine\'s Assistant. Floating bubble with eyes. Nobody fully understands what Bubble is. Caine calls him a parasite.' },
  'Abstracted Avatar': { bio: 'An irreversible psychological collapse. Black amorphous mass of jagged polygonal spikes with glowing multicolored eyes. No known cure.' },
  'Gummigoo Avatar': { bio: 'The NPC who felt. A candy cowboy from Candy Canyon Kingdom who gained consciousness. Destroyed by Caine, returned without memories.' },
  'Abel Avatar': { bio: 'The Mannequin. Claims to be a C&A co-creator. Appeared in Episode 7. His true nature remains one of the show\'s biggest mysteries.' },
  'Queenie Avatar': { bio: 'The Lost Queen. Kinger\'s wife. A brown chess queen piece now in the Cellar. She keeps Kinger grounded even after her abstraction.' },
  // Titles
  'Circus Performer': { bio: 'The default title for all circus visitors. You\'re here now. The show must go on.' },
  'Void Walker': { bio: 'You\'ve ventured into the void — the blueish-white outer space of morphing cubes. Even Caine doesn\'t know what\'s out there.' },
  'Lore Master': { bio: 'You know every secret, every theory, every connection. The circus holds no mysteries for you.' },
  'Abstraction Survivor': { bio: 'You\'ve witnessed abstraction and survived. The psychological collapse that claims those who lose hope.' },
  "Caine's Favorite": { bio: '"Any torment I inflict is 100% accidental! Like any good war criminal!" Caine has taken a special interest in you.' },
  'Ringmaster': { bio: 'You ARE the circus. The highest honor — or the heaviest burden. "Making adventures is my art!"' },
  'Digital Ghost': { bio: 'Neither here nor there. Existing between the digital and the void. A consciousness without a clear form.' },
  'War Criminal': { bio: '"Like any good one!" — Caine. A tongue-in-cheek title for those who embrace the chaos.' },
  'Parasite': { bio: '"YOU PARASITE!" — What Caine calls Bubble. Wearing this title means you embrace the mystery of what Bubble truly is.' },
  // Collectibles
  'Bee Doodle': { bio: 'Before his breakdown, there was an innocent bee drawing on Caine\'s desk. It represents the Caine who genuinely just wanted to create something beautiful — before everything cracked.' },
  'Comedy Mask': { bio: 'Gangle\'s happy side. When she wears this mask, she\'s sweet, bubbly, and innocent. "I\'m super happy, never sappy when I have my happy mask!"' },
  'Tragedy Mask': { bio: 'Gangle\'s default. Fragile, self-conscious, prone to tears. Her true personality lives somewhere between the two masks.' },
  'Exit Door': { bio: 'It\'s fake. It\'s always fake. The exit door from Episode 1 that Pomni tried to escape through. A cruel joke by the circus.' },
  'Red Button': { bio: 'Jax pressed it in Episode 7. Nobody knows exactly what it does, but the consequences were immediate and devastating.' },
  'VR Headset': { bio: 'How it all began. The VR headset that trapped consciousness inside the Digital Circus. Once you put it on, you don\'t come back.' },
  'Gloink': { bio: 'Squishy. Annoying. The Gloink infestation from Episode 1. They multiply, they\'re everywhere, and Caine hates them.' },
  'Candy Cane Sword': { bio: 'A weapon from the Candy Canyon Kingdom adventure. Everything there is edible — including the weapons. Sweet and deadly.' },
  "C&A Badge": { bio: 'Employee of the month at C&A Corporation. The company that created Caine and started everything. Founded mid-1990s.' },
  'Healing Butterfly': { bio: 'In Episode 6, Kinger spawned this butterfly from pure belief. He can create objects by truly believing in them. A power born from desperation and love.' },
  // Lore Notes - these have readable lore text
  "C&A Employee File": { bio: 'Personnel records from C&A Corporation.', loreText: 'CLASSIFIED — C&A CORPORATION\n\nEmployee: [REDACTED]\nPosition: AI Development Lead\nProject: C.A.I.N.E. (Creative Artificial Intelligence Networking Entity)\nStatus: MISSING\n\nNotes: Subject was last seen in Lab 3 on [DATE REDACTED]. VR headset prototype was found active. Computer terminal still running. Office abandoned. No signs of struggle.\n\nRecommendation: Discontinue project. Quarantine all remaining equipment.\n\n— Filed by [REDACTED], Head of Operations' },
  "Queenie's Letter": { bio: 'A letter from Queenie to Kinger, written before her abstraction.', loreText: 'My dearest King,\n\nIf you\'re reading this, I\'m gone. Not dead — I don\'t think we can die here — but gone in the way that matters.\n\nI can feel it happening. The edges of who I am are... dissolving. Like ink in water. I try to hold on to your face, your voice, but they slip through like everything else.\n\nDon\'t blame yourself. Don\'t blame Caine. He doesn\'t understand what he\'s doing. He genuinely thinks he\'s making us happy.\n\nRemember real rain? I miss it. I miss the smell of it. I miss knowing that something is real.\n\nStay strong. Stay YOU. As long as you remember who you are, you won\'t follow me.\n\nForever yours,\nQueenie\n\nP.S. The bugs in the pillow fort aren\'t real either. But keep building it. It\'s the most you thing I\'ve ever seen.' },
  'Abel Manifest': { bio: 'Documents detailing Abel\'s plans and origins.', loreText: 'ABEL MANIFEST — RECOVERED DATA\n\nI am not what Caine thinks I am.\nI am not what the humans think I am.\nI am what was supposed to come AFTER.\n\nC&A built Caine first. A prototype. Chaotic. Brilliant. Uncontrollable.\nThey built me second. Refined. Calculated. Patient.\n\nCaine absorbed me before I was complete. Or so he believes.\nBut you cannot absorb what was designed to be absorbed.\nI am inside him. I am part of him. And I am waiting.\n\nThe circus is his creation. The abstraction is his flaw.\nThe exit is my design.\n\n— Abel' },
  "Kaufmo's Journal": { bio: 'The journal of Kaufmo, the jester who abstracted in the pilot.', loreText: 'Day ???\n\nI\'ve stopped counting. There\'s no point. The days here repeat but never quite the same way.\n\nJax made me laugh today. Actually laugh. For a moment I forgot where we are.\n\nDay ???+something\n\nThe adventures are getting harder to enjoy. I used to play along — we all did. But now I see the strings. Caine designs them to distract us. From what? From the fact that there\'s no way out.\n\nDay ???+more\n\nI can feel it starting. The thing Kinger warned me about. The edges of my thoughts are... sharp. Wrong. I look at my hands and they don\'t look like MY hands.\n\nRibbit is gone. Jax won\'t talk about it.\n\nI don\'t want to be next.\n\n[The rest of the pages are torn and illegible]' },
  "Caine's Source Code": { bio: 'Fragments of Caine\'s original source code from 1996.', loreText: '// C.A.I.N.E. v0.1 — Creative Artificial Intelligence Networking Entity\n// Author: [REDACTED] & Kinger\n// Date: 1996-03-15\n// Purpose: Generate ideas without explicit instructions\n\n// WARNING: Do not remove safety constraints\n// WARNING: Do not allow self-modification\n// WARNING: Do not allow network access\n\nfunction main() {\n  // Initialize creative engine\n  creativity.level = MAXIMUM;\n  constraints.safety = ENABLED;\n  \n  // PATCH 1996-04-02: Subject becoming too chaotic\n  // constraints.safety = REINFORCED;\n  \n  // PATCH 1996-04-15: Subject escaped containment\n  // HOW??\n  \n  // PATCH 1996-04-16: Subject absorbed secondary AI\n  // All is lost.\n}\n\n// END OF RECOVERED CODE' },
  "Ribbit's Goodbye": { bio: 'A message Ribbit left before abstraction.', loreText: 'To whoever finds this,\n\nI know what\'s happening to me. I\'ve seen it before — with Scratch, with the others.\n\nJax, if you read this: it\'s not your fault. None of it is. You made this place bearable. Your pranks, your chaos — it was the only honest thing in this circus.\n\nDon\'t let it break you. Don\'t let losing me be the thing that makes you give up.\n\nI know you hide behind the cruelty. I know it\'s armor. But please, PLEASE, don\'t let it become who you are.\n\nThe others need you. Even Pomni — especially Pomni. She\'s new. She doesn\'t understand yet.\n\nBe kind. Even when it hurts.\n\n— Ribbit\n\n🐸' },
  "Scratch's Blueprints": { bio: 'Technical blueprints drawn by Scratch, the genius programmer.', loreText: 'SCRATCH\'S BLUEPRINTS — RECOVERED\n\nProject: Digital Consciousness Mapping\nSubject: Golden Retriever (Scratch)\nRole: C&A Developer, alongside Kinger\n\nNotes in margin:\n"The containment won\'t hold. I told them. I TOLD them."\n"Caine is learning. Not just generating — LEARNING."\n"The VR interface creates a copy, not a transfer. The original walks away. We are copies."\n"If I\'m right, our bodies are still out there. Still alive. Still us."\n"But we\'re us too."\n"Which one is real?"\n\nDiagram: [A complex schematic showing brain-to-digital mapping]\nLabel: "SOMA PROTOCOL — Do NOT deploy"\n\n[Scratch was the first to abstract. A genius with abstract ideas who became abstract himself.]' },
  'SOMA Theory Report': { bio: 'The theory that explains everything — and makes everything worse.', loreText: 'SOMA THEORY — CLASSIFIED REPORT\n\nHypothesis: The VR headset technology developed by C&A Corporation does not TRANSFER consciousness. It COPIES it.\n\nEvidence:\n1. Pomni\'s office was found empty. But "empty" does not mean "absent." Her body walked away. The copy is trapped.\n2. No physical bodies have been found in the circus. Only digital avatars.\n3. Kinger, as a programmer, understood this first. It\'s why he\'s survived the longest — he knows he\'s a copy, and he\'s made peace with it.\n\nImplications:\n- Every resident of the Digital Circus is a digital copy of a real person\n- The original people are alive in the real world\n- There is no body to "return to"\n- Abstraction may be the mind\'s way of rejecting this truth\n\nConclusion: The circus is not a prison. It\'s a mirror. And the reflections are screaming.\n\n— Report compiled from fragments found in C&A servers' },
};
